name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        build-root-directory: Kroy
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add Permission
      run: chmod +x Kroy/gradlew
    - name: Build with Gradle
      run: ./Kroy/gradlew -p Kroy desktop:dist
